# Site settings
author: Jack Quinoa
title: Jack's Blog
header-img: img/home-bg.png
email: jquinoa208@gmail.com
copyright_name: Jack Quinoa
description: > # this means to ignore newlines until "baseurl:"
  Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  JackQuinoa

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
